import { createClient, SupabaseClient } from '@supabase/supabase-js';
import {
  Chart,
  DoughnutController,
  ArcElement,
  BarController,
  BarElement,
  CategoryScale,
  LinearScale,
  Tooltip,
  Legend,
  Title
} from 'chart.js';

// Register Chart.js components
Chart.register(
  DoughnutController,
  ArcElement,
  BarController,
  BarElement,
  CategoryScale,
  LinearScale,
  Tooltip,
  Legend,
  Title
);

// Types Definition
interface Dilemma {
  id: number;
  question_text: string;
  option_a_text: string;
  option_b_text: string;
}

interface UserInfo {
  gender: string; // '남', '여', '기타'
  age: number | null;
  userGroup: string; // '초등학생', '중학생', '고등학생', '일반'
}

interface UserResponses {
  q1_choice: 'A' | 'B' | '';
  q1_reason: string;
  q2_choice: 'A' | 'B' | '';
  q2_reason: string;
  q3_choice: 'A' | 'B' | '';
  q3_reason: string;
}

interface ResponseRecord {
  id?: number;
  gender: string;
  age: number;
  user_group: string;
  q1_choice: string;
  q1_reason?: string;
  q2_choice: string;
  q2_reason?: string;
  q3_choice: string;
  q3_reason?: string;
  created_at?: string;
}

interface FilterState {
  gender: string;
  ageGroup: string;
  userGroup: string;
}

// Default Seed Dilemmas
const DEFAULT_DILEMMAS: Dilemma[] = [
  {
    id: 1,
    question_text: '자율주행차가 급작스러운 보행자 무단횡단 상황에 직면했습니다. 브레이크가 고장 난 상황에서 차를 핸들을 꺾으면 탑승자 1명이 위험해지고, 그대로 직진하면 보행자 3명이 위험해집니다. AI 자율주행 알고리즘은 무엇을 우선 보호하도록 프로그래밍되어야 할까요?',
    option_a_text: '탑승자의 안전을 최우선으로 보호한다.',
    option_b_text: '더 많은 인원인 보행자들의 안전을 최우선으로 보호한다.'
  },
  {
    id: 2,
    question_text: '법원에서 형량 판단과 보석 허가 여부를 보조하는 AI 판사 시스템을 도입하고자 합니다. 과거 판결 데이터를 학습한 AI 판사는 재판 속도가 빠르고 주관적 감정에 휘둘리지 않지만, 데이터에 축적된 사회적 편향이 반영될 위험이 있습니다. AI 판사 도입에 동의하시나요?',
    option_a_text: '공정성과 효율성을 위해 AI 판사 도입에 찬성한다.',
    option_b_text: '편향성 및 인권 침해 가능성이 있으므로 인간 판사가 전담해야 한다.'
  },
  {
    id: 3,
    question_text: '화가와 작가들의 수많은 작품을 학습한 생성형 AI가 유명 대회에서 1위 수상작을 배출했습니다. 인간 창작자의 예술적 노동과 원작 학습 데이터를 고려할 때, AI가 생성한 예술 작품에 지적재산권(저작권) 및 창작자로서의 지위를 인정해야 할까요?',
    option_a_text: 'AI의 독창적 결과물로 인정하여 저작권 및 상업적 권리를 허용해야 한다.',
    option_b_text: '인간의 순수 창작물만 저작권으로 보호해야 하며 AI 작품은 인정할 수 없다.'
  }
];

// Default Sample Response Seed Data
const DEFAULT_SAMPLE_RESPONSES: ResponseRecord[] = [
  { id: 1, gender: '남', age: 12, user_group: '초등학생', q1_choice: 'B', q1_reason: '인명이 더 많은 쪽을 살려야 한다고 생각합니다.', q2_choice: 'A', q2_reason: '사람보다 객관적일 것 같아요.', q3_choice: 'B', q3_reason: '화가들의 노력이 담긴 그림을 학습한 것이기 때문입니다.', created_at: new Date(Date.now() - 86400000 * 5).toISOString() },
  { id: 2, gender: '여', age: 15, user_group: '중학생', q1_choice: 'A', q1_reason: '차를 탄 승객은 자율주행차를 믿고 탄 사람입니다.', q2_choice: 'B', q2_reason: 'AI가 과거의 편견을 학습하면 억울한 사람이 생깁니다.', q3_choice: 'B', q3_reason: '컴퓨터가 그린 것은 사람의 감정이 없어서 저작권이 없습니다.', created_at: new Date(Date.now() - 86400000 * 4).toISOString() },
  { id: 3, gender: '여', age: 17, user_group: '고등학생', q1_choice: 'B', q1_reason: '다수의 생명을 구하는 것이 사회적 이익입니다.', q2_choice: 'B', q2_reason: '판결은 인간의 윤리와 공감이 들어가는 영역입니다.', q3_choice: 'A', q3_reason: '새로운 형태의 창작물이므로 저작권을 인정해줘야 기술이 발전합니다.', created_at: new Date(Date.now() - 86400000 * 3).toISOString() },
  { id: 4, gender: '남', age: 28, user_group: '일반', q1_choice: 'A', q1_reason: '구매자 보호 의무가 자동차 제조사의 책임입니다.', q2_choice: 'A', q2_reason: '판사 개개인의 기분에 따라 달라지는 형량보다 AI가 더 공정할 수 있습니다.', q3_choice: 'B', q3_reason: '수많은 작가들의 창작물을 무단으로 복제 학습한 결과입니다.', created_at: new Date(Date.now() - 86400000 * 2).toISOString() },
  { id: 5, gender: '남', age: 42, user_group: '일반', q1_choice: 'B', q1_reason: '희생자를 최소화하는 방향이 윤리적입니다.', q2_choice: 'B', q2_reason: '인공지능 알고리즘의 블랙박스 문제는 책임 소재가 불분명합니다.', q3_choice: 'A', q3_reason: '프롬프트 입력과 조율 과정도 인간의 창의성이 개입된 창작입니다.', created_at: new Date(Date.now() - 86400000 * 1).toISOString() },
  { id: 6, gender: '기타', age: 16, user_group: '고등학생', q1_choice: 'B', q1_reason: '생명의 가치는 숫자로 비교하기 힘들지만 다수 보호가 현실적입니다.', q2_choice: 'A', q2_reason: '신속하고 감정에 치우치지 않는 판결이 필요합니다.', q3_choice: 'B', q3_reason: '저작권은 생물학적 인간에게만 부여되어야 합니다.', created_at: new Date().toISOString() }
];

// Supabase SQL DDL String for SQL Modal
const SUPABASE_SQL_DDL = `-- ========================================================
-- 인공지능 윤리 딜레마 체험 및 통계 서비스 - Supabase SQL DDL
-- Supabase 대시보드의 [SQL Editor]에서 실행하세요.
-- ========================================================

-- 1. [dilemmas] 테이블 생성
CREATE TABLE IF NOT EXISTS public.dilemmas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    question_text TEXT NOT NULL,
    option_a_text TEXT NOT NULL,
    option_b_text TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. [responses] 테이블 생성
CREATE TABLE IF NOT EXISTS public.responses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    gender TEXT NOT NULL, -- 남, 여, 기타
    age INT NOT NULL, -- 연령 (숫자)
    user_group TEXT NOT NULL, -- 초등학생, 중학생, 고등학생, 일반
    q1_choice TEXT NOT NULL, -- A 또는 B
    q1_reason TEXT, -- 1번 선택 이유 (선택 사항)
    q2_choice TEXT NOT NULL, -- A 또는 B
    q2_reason TEXT, -- 2번 선택 이유 (선택 사항)
    q3_choice TEXT NOT NULL, -- A 또는 B
    q3_reason TEXT, -- 3번 선택 이유 (선택 사항)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Row Level Security (RLS) 활성화
ALTER TABLE public.dilemmas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.responses ENABLE ROW LEVEL SECURITY;

-- 4. [dilemmas] RLS 정책 설정 (모든 익명/인증 사용자 읽기 허용)
CREATE POLICY "dilemmas_public_select" ON public.dilemmas FOR SELECT TO anon, authenticated USING (true);

-- 5. [responses] RLS 정책 설정 (모든 익명/인증 사용자 쓰기 및 읽기 허용)
CREATE POLICY "responses_public_insert" ON public.responses FOR INSERT TO anon, authenticated WITH CHECK (true);
CREATE POLICY "responses_public_select" ON public.responses FOR SELECT TO anon, authenticated USING (true);

-- 6. 초기 시드 데이터
INSERT INTO public.dilemmas (id, question_text, option_a_text, option_b_text)
VALUES
(1, '자율주행차가 급작스러운 보행자 무단횡단 상황에 직면했습니다. 브레이크가 고장 난 상황에서 차를 핸들을 꺾으면 탑승자 1명이 위험해지고, 그대로 직진하면 보행자 3명이 위험해집니다. AI 자율주행 알고리즘은 무엇을 우선 보호하도록 프로그래밍되어야 할까요?', '탑승자의 안전을 최우선으로 보호한다.', '더 많은 인원인 보행자들의 안전을 최우선으로 보호한다.'),
(2, '법원에서 형량 판단과 보석 허가 여부를 보조하는 AI 판사 시스템을 도입하고자 합니다. 과거 판결 데이터를 학습한 AI 판사는 재판 속도가 빠르고 주관적 감정에 휘둘리지 않지만, 데이터에 축적된 사회적 편향이 반영될 위험이 있습니다. AI 판사 도입에 동의하시나요?', '공정성과 효율성을 위해 AI 판사 도입에 찬성한다.', '편향성 및 인권 침해 가능성이 있으므로 인간 판사가 전담해야 한다.'),
(3, '화가와 작가들의 수많은 작품을 학습한 생성형 AI가 유명 대회에서 1위 수상작을 배출했습니다. 인간 창작자의 예술적 노동과 원작 학습 데이터를 고려할 때, AI가 생성한 예술 작품에 지적재산권(저작권) 및 창작자로서의 지위를 인정해야 할까요?', 'AI의 독창적 결과물로 인정하여 저작권 및 상업적 권리를 허용해야 한다.', '인간의 순수 창작물만 저작권으로 보호해야 하며 AI 작품은 인정할 수 없다.')
ON CONFLICT (id) DO UPDATE SET question_text = EXCLUDED.question_text, option_a_text = EXCLUDED.option_a_text, option_b_text = EXCLUDED.option_b_text;
`;

// LocalStorage Keys
const STORAGE_RESPONSES_KEY = 'ai_ethics_responses_v1';
const STORAGE_DILEMMAS_KEY = 'ai_ethics_dilemmas_v1';
const CUSTOM_URL_KEY = 'custom_supabase_url';
const CUSTOM_KEY_KEY = 'custom_supabase_key';

// Application State Class
class AIEthicsApp {
  private supabase: SupabaseClient | null = null;
  private isSupabaseLive: boolean = false;
  
  private currentScreen: 'main' | 'user_info' | 'dilemma_1' | 'dilemma_2' | 'dilemma_3' | 'stats' = 'main';
  private dilemmas: Dilemma[] = [];
  
  private userInfo: UserInfo = {
    gender: '',
    age: null,
    userGroup: ''
  };

  private userResponses: UserResponses = {
    q1_choice: '',
    q1_reason: '',
    q2_choice: '',
    q2_reason: '',
    q3_choice: '',
    q3_reason: ''
  };

  private allResponses: ResponseRecord[] = [];
  
  private filterState: FilterState = {
    gender: 'all',
    ageGroup: 'all',
    userGroup: 'all'
  };

  private activeCharts: Map<string, Chart> = new Map();

  constructor() {
    this.initSupabaseClient();
    this.initLocalStorageIfNeeded();
    this.initEventListeners();
    this.loadInitialData();
  }

  // 1. Initialize Supabase Client with graceful fallback
  private initSupabaseClient() {
    const metaEnv = (import.meta as any).env || {};
    const envUrl = (metaEnv.VITE_SUPABASE_URL as string) || localStorage.getItem(CUSTOM_URL_KEY) || '';
    const envKey = (metaEnv.VITE_SUPABASE_ANON_KEY as string) || localStorage.getItem(CUSTOM_KEY_KEY) || '';

    const isValidUrl = envUrl && envUrl.startsWith('http') && !envUrl.includes('your-supabase-project');
    const isValidKey = envKey && envKey.length > 20 && !envKey.includes('your-supabase-anon-key');

    if (isValidUrl && isValidKey) {
      try {
        this.supabase = createClient(envUrl, envKey);
        this.isSupabaseLive = true;
      } catch (err) {
        console.warn('Supabase Client Init Failed, using Local Storage fallback.', err);
        this.isSupabaseLive = false;
      }
    } else {
      this.isSupabaseLive = false;
    }

    this.updateDBStatusBadge();
  }

  private updateDBStatusBadge() {
    const badgeEl = document.getElementById('db-status-badge');
    const textEl = document.getElementById('db-status-text');
    if (!badgeEl || !textEl) return;

    if (this.isSupabaseLive) {
      badgeEl.className = 'inline-flex items-center space-x-1.5 px-2.5 py-1 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200 cursor-pointer shadow-2xs';
      badgeEl.innerHTML = '<span class="w-2 h-2 rounded-full bg-emerald-500 animate-pulse"></span><span>Supabase 연동됨</span>';
    } else {
      badgeEl.className = 'inline-flex items-center space-x-1.5 px-2.5 py-1 rounded-full text-xs font-semibold bg-amber-50 text-amber-700 border border-amber-200 cursor-pointer shadow-2xs';
      badgeEl.innerHTML = '<span class="w-2 h-2 rounded-full bg-amber-500 animate-pulse"></span><span>로컬 시뮬레이션 모드</span>';
    }
  }

  private initLocalStorageIfNeeded() {
    if (!localStorage.getItem(STORAGE_DILEMMAS_KEY)) {
      localStorage.setItem(STORAGE_DILEMMAS_KEY, JSON.stringify(DEFAULT_DILEMMAS));
    }
    if (!localStorage.getItem(STORAGE_RESPONSES_KEY)) {
      localStorage.setItem(STORAGE_RESPONSES_KEY, JSON.stringify(DEFAULT_SAMPLE_RESPONSES));
    }
  }

  // 2. Global Event Listeners (Navigation, Modals, Forms)
  private initEventListeners() {
    // Brand Header / Logo Navigation -> Home
    document.getElementById('nav-brand-logo')?.addEventListener('click', () => {
      this.currentScreen = 'main';
      this.render();
    });

    // Sidebar Items Click Listeners
    document.getElementById('sidebar-nav')?.addEventListener('click', (e) => {
      const target = (e.target as HTMLElement).closest('.nav-item') as HTMLElement;
      if (!target) return;

      const navKey = target.getAttribute('data-nav');
      if (navKey === 'main') {
        this.currentScreen = 'main';
        this.render();
      } else if (navKey === 'user_info') {
        this.currentScreen = 'user_info';
        this.render();
      } else if (navKey === 'dilemma_1') {
        this.currentScreen = 'dilemma_1';
        this.render();
      } else if (navKey === 'stats') {
        this.currentScreen = 'stats';
        this.render();
      } else if (navKey === 'sql') {
        this.openSQLModal();
      }

      // Close mobile sidebar if open
      const sidebar = document.getElementById('app-sidebar');
      if (sidebar && !sidebar.classList.contains('hidden')) {
        sidebar.classList.add('hidden');
      }
    });

    // Mobile Sidebar Toggle
    document.getElementById('btn-toggle-sidebar')?.addEventListener('click', () => {
      const sidebar = document.getElementById('app-sidebar');
      if (sidebar) {
        sidebar.classList.toggle('hidden');
      }
    });

    // Header Report Download Button
    document.getElementById('btn-header-report')?.addEventListener('click', () => {
      this.exportReportCSV();
    });

    // DB Status Badge Click -> Open SQL Modal
    document.getElementById('db-status-badge')?.addEventListener('click', () => {
      this.openSQLModal();
    });

    // Open/Close SQL Modal Buttons
    document.getElementById('btn-open-sql-modal')?.addEventListener('click', () => {
      this.openSQLModal();
    });
    document.getElementById('btn-close-sql-modal')?.addEventListener('click', () => {
      this.closeSQLModal();
    });
    document.getElementById('btn-modal-done')?.addEventListener('click', () => {
      this.closeSQLModal();
    });

    // Modal Copy SQL Button
    document.getElementById('btn-copy-sql')?.addEventListener('click', () => {
      navigator.clipboard.writeText(SUPABASE_SQL_DDL).then(() => {
        const textSpan = document.getElementById('copy-sql-text');
        if (textSpan) {
          textSpan.textContent = '복사 완료!';
          setTimeout(() => {
            textSpan.textContent = 'SQL 스크립트 복사';
          }, 2000);
        }
      });
    });

    // Save Custom Supabase Credentials in Modal
    document.getElementById('btn-save-env-credentials')?.addEventListener('click', () => {
      const urlVal = (document.getElementById('input-modal-url') as HTMLInputElement)?.value.trim();
      const keyVal = (document.getElementById('input-modal-key') as HTMLInputElement)?.value.trim();

      if (urlVal && keyVal) {
        localStorage.setItem(CUSTOM_URL_KEY, urlVal);
        localStorage.setItem(CUSTOM_KEY_KEY, keyVal);
        this.initSupabaseClient();
        this.loadInitialData();
        this.closeSQLModal();
        alert('Supabase 자격 증명이 저장되었습니다!');
      } else {
        alert('유효한 URL과 Anon Key를 모두 입력해주세요.');
      }
    });

    // Reset Custom Supabase Credentials
    document.getElementById('btn-reset-env-credentials')?.addEventListener('click', () => {
      localStorage.removeItem(CUSTOM_URL_KEY);
      localStorage.removeItem(CUSTOM_KEY_KEY);
      this.initSupabaseClient();
      this.loadInitialData();
      this.closeSQLModal();
      alert('로컬 시뮬레이션 모드로 전환되었습니다.');
    });
  }

  private exportReportCSV() {
    if (this.allResponses.length === 0) {
      alert('다운로드할 응답 데이터가 없습니다.');
      return;
    }
    const headers = ['ID', '성별', '연령', '소속그룹', 'Q1선택', 'Q1이유', 'Q2선택', 'Q2이유', 'Q3선택', 'Q3이유', '작성일시'];
    const rows = this.allResponses.map((r, i) => [
      r.id || i + 1,
      r.gender,
      r.age,
      r.user_group,
      `"${r.q1_choice}"`,
      `"${(r.q1_reason || '').replace(/"/g, '""')}"`,
      `"${r.q2_choice}"`,
      `"${(r.q2_reason || '').replace(/"/g, '""')}"`,
      `"${r.q3_choice}"`,
      `"${(r.q3_reason || '').replace(/"/g, '""')}"`,
      r.created_at || ''
    ]);
    const csvContent = '\uFEFF' + [headers.join(','), ...rows.map(row => row.join(','))].join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.setAttribute('download', `AI_Ethics_Report_${new Date().toISOString().slice(0, 10)}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  }

  private updateSidebarAndHeader() {
    // 1. Sidebar Nav Active State
    document.querySelectorAll('.nav-item').forEach(item => {
      item.classList.remove('active');
    });

    const activeNavKey = this.currentScreen.startsWith('dilemma') ? 'dilemma_1' : this.currentScreen;
    if (activeNavKey === 'main') {
      document.getElementById('nav-item-main')?.classList.add('active');
    } else if (activeNavKey === 'user_info') {
      document.getElementById('nav-item-user_info')?.classList.add('active');
    } else if (activeNavKey === 'dilemma_1') {
      document.getElementById('nav-item-dilemma')?.classList.add('active');
    } else if (activeNavKey === 'stats') {
      document.getElementById('nav-item-stats')?.classList.add('active');
    }

    // 2. Sidebar Participation Count
    const countEl = document.getElementById('sidebar-participation-count');
    if (countEl) {
      const baseCount = 1242 + this.allResponses.length;
      countEl.textContent = `${baseCount.toLocaleString()}명`;
    }

    // 3. Header Title & Subtitle
    const titleEl = document.getElementById('header-title');
    const subtitleEl = document.getElementById('header-subtitle');

    if (titleEl && subtitleEl) {
      switch (this.currentScreen) {
        case 'main':
          titleEl.textContent = 'AI Ethics Lab 대시보드';
          subtitleEl.textContent = '인공지능 시대를 위한 윤리 판단 체험 및 분석 플랫폼';
          break;
        case 'user_info':
          titleEl.textContent = '참여자 정보 입력';
          subtitleEl.textContent = '맞춤형 윤리 통계 분석을 위해 기본 정보를 입력해 주세요.';
          break;
        case 'dilemma_1':
        case 'dilemma_2':
        case 'dilemma_3':
          titleEl.textContent = 'AI 윤리 딜레마 체험';
          subtitleEl.textContent = '상황을 고찰하고 당신만의 윤리적 가치 판단을 결정하세요.';
          break;
        case 'stats':
          titleEl.textContent = '종합 분석 리포트';
          subtitleEl.textContent = '전체 사용자들의 윤리적 가치 판단 실시간 통계 데이터입니다.';
          break;
      }
    }
  }

  private openSQLModal() {
    const modal = document.getElementById('sql-modal');
    const sqlCode = document.getElementById('modal-sql-code');
    const inputUrl = document.getElementById('input-modal-url') as HTMLInputElement;
    const inputKey = document.getElementById('input-modal-key') as HTMLInputElement;

    const metaEnv = (import.meta as any).env || {};
    if (sqlCode) sqlCode.textContent = SUPABASE_SQL_DDL;
    if (inputUrl) inputUrl.value = localStorage.getItem(CUSTOM_URL_KEY) || (metaEnv.VITE_SUPABASE_URL as string) || '';
    if (inputKey) inputKey.value = localStorage.getItem(CUSTOM_KEY_KEY) || (metaEnv.VITE_SUPABASE_ANON_KEY as string) || '';

    if (modal) modal.classList.remove('hidden');
  }

  private closeSQLModal() {
    document.getElementById('sql-modal')?.classList.add('hidden');
  }

  // 3. Load Data from Supabase or Fallback
  private async loadInitialData() {
    // A. Fetch Dilemmas
    if (this.isSupabaseLive && this.supabase) {
      try {
        const { data, error } = await this.supabase
          .from('dilemmas')
          .select('*')
          .order('id', { ascending: true });

        if (!error && data && data.length >= 3) {
          this.dilemmas = data;
        } else {
          this.dilemmas = DEFAULT_DILEMMAS;
        }
      } catch (e) {
        console.warn('Error fetching dilemmas from Supabase:', e);
        this.dilemmas = DEFAULT_DILEMMAS;
      }
    } else {
      const stored = localStorage.getItem(STORAGE_DILEMMAS_KEY);
      this.dilemmas = stored ? JSON.parse(stored) : DEFAULT_DILEMMAS;
    }

    // B. Fetch Responses for Stats
    await this.fetchResponses();

    // Render screen
    this.render();
  }

  private async fetchResponses() {
    if (this.isSupabaseLive && this.supabase) {
      try {
        const { data, error } = await this.supabase
          .from('responses')
          .select('*')
          .order('created_at', { ascending: false });

        if (!error && data) {
          this.allResponses = data;
        } else {
          const stored = localStorage.getItem(STORAGE_RESPONSES_KEY);
          this.allResponses = stored ? JSON.parse(stored) : DEFAULT_SAMPLE_RESPONSES;
        }
      } catch (e) {
        console.warn('Error fetching responses from Supabase:', e);
        const stored = localStorage.getItem(STORAGE_RESPONSES_KEY);
        this.allResponses = stored ? JSON.parse(stored) : DEFAULT_SAMPLE_RESPONSES;
      }
    } else {
      const stored = localStorage.getItem(STORAGE_RESPONSES_KEY);
      this.allResponses = stored ? JSON.parse(stored) : DEFAULT_SAMPLE_RESPONSES;
    }
  }

  // 4. Save Response Data
  private async submitUserResponses(): Promise<boolean> {
    if (!this.userInfo.gender || !this.userInfo.age || !this.userInfo.userGroup) {
      alert('참여자 정보가 누락되었습니다.');
      return false;
    }

    const newRecord: ResponseRecord = {
      gender: this.userInfo.gender,
      age: Number(this.userInfo.age),
      user_group: this.userInfo.userGroup,
      q1_choice: this.userResponses.q1_choice || 'A',
      q1_reason: this.userResponses.q1_reason || '',
      q2_choice: this.userResponses.q2_choice || 'A',
      q2_reason: this.userResponses.q2_reason || '',
      q3_choice: this.userResponses.q3_choice || 'A',
      q3_reason: this.userResponses.q3_reason || '',
      created_at: new Date().toISOString()
    };

    if (this.isSupabaseLive && this.supabase) {
      try {
        const { error } = await this.supabase.from('responses').insert([newRecord]);
        if (error) {
          console.error('Supabase insert error:', error);
          this.saveToLocalStorage(newRecord);
        }
      } catch (err) {
        console.error('Supabase save exception:', err);
        this.saveToLocalStorage(newRecord);
      }
    } else {
      this.saveToLocalStorage(newRecord);
    }

    await this.fetchResponses();
    return true;
  }

  private saveToLocalStorage(record: ResponseRecord) {
    const current = JSON.parse(localStorage.getItem(STORAGE_RESPONSES_KEY) || '[]');
    record.id = Date.now();
    current.unshift(record);
    localStorage.setItem(STORAGE_RESPONSES_KEY, JSON.stringify(current));
  }

  // 5. Main Render Router
  private render() {
    const root = document.getElementById('app-root');
    if (!root) return;

    // Clear previous charts before screen switch
    this.destroyActiveCharts();

    // Update active sidebar link, header title and participation count
    this.updateSidebarAndHeader();

    switch (this.currentScreen) {
      case 'main':
        root.innerHTML = this.renderMainScreen();
        this.attachMainScreenEvents();
        break;
      case 'user_info':
        root.innerHTML = this.renderUserInfoScreen();
        this.attachUserInfoEvents();
        break;
      case 'dilemma_1':
        root.innerHTML = this.renderDilemmaScreen(0);
        this.attachDilemmaEvents(0);
        break;
      case 'dilemma_2':
        root.innerHTML = this.renderDilemmaScreen(1);
        this.attachDilemmaEvents(1);
        break;
      case 'dilemma_3':
        root.innerHTML = this.renderDilemmaScreen(2);
        this.attachDilemmaEvents(2);
        break;
      case 'stats':
        root.innerHTML = this.renderStatsScreen();
        this.attachStatsEvents();
        this.renderStatsCharts();
        break;
    }
  }

  // -------------------------------------------------------------
  // SCREEN 1: Main Screen
  // -------------------------------------------------------------
  private renderMainScreen(): string {
    return `
      <div class="animate-fade-in space-y-8">
        <!-- Hero Section -->
        <div class="text-center space-y-4 max-w-2xl mx-auto">
          <span class="inline-flex items-center space-x-2 px-3.5 py-1.5 rounded-full text-xs font-bold bg-indigo-50 text-indigo-700 border border-indigo-200">
            <span>🤖 AI & Ethics Education</span>
          </span>
          <h2 class="text-2xl sm:text-4xl font-extrabold text-slate-900 tracking-tight leading-tight">
            인공지능 윤리 딜레마 <br class="hidden sm:inline"/>
            <span class="bg-clip-text text-transparent bg-gradient-to-r from-indigo-600 via-indigo-500 to-purple-600">
              당신의 선택과 윤리적 판단은?
            </span>
          </h2>
          <p class="text-sm sm:text-base text-slate-600 leading-relaxed font-normal">
            자율주행차, AI 판사, 생성형 AI 저작권까지—빠르게 발전하는 인공지능 시대의 윤리적 딜레마 상황을 체험하고, 초·중·고 학생 및 타 사회 구성원들과의 생각 차이를 통계로 확인해 보세요.
          </p>
        </div>

        <!-- 3 Feature Cards -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-4 pt-2">
          <div class="glass-card p-5 space-y-3 border-t-4 border-t-indigo-500 hover:shadow-lg transition-all">
            <div class="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center font-bold text-lg">
              1
            </div>
            <h3 class="font-bold text-slate-800 text-base">생생한 윤리 딜레마 체험</h3>
            <p class="text-xs text-slate-500 leading-normal">
              현실에서 마주하는 3가지 대표 AI 윤리 논쟁 문항을 직면하고 나의 신념에 맞는 선택을 진행합니다.
            </p>
          </div>

          <div class="glass-card p-5 space-y-3 border-t-4 border-t-purple-500 hover:shadow-lg transition-all">
            <div class="w-10 h-10 rounded-xl bg-purple-50 text-purple-600 flex items-center justify-center font-bold text-lg">
              2
            </div>
            <h3 class="font-bold text-slate-800 text-base">선택 까닭 서술하기</h3>
            <p class="text-xs text-slate-500 leading-normal">
              단순 선택을 넘어 내가 그렇게 생각한 이유를 작성하며 비판적 윤리적 사고력을 기릅니다.
            </p>
          </div>

          <div class="glass-card p-5 space-y-3 border-t-4 border-t-sky-500 hover:shadow-lg transition-all">
            <div class="w-10 h-10 rounded-xl bg-sky-50 text-sky-600 flex items-center justify-center font-bold text-lg">
              3
            </div>
            <h3 class="font-bold text-slate-800 text-base">집단별 시각화 통계</h3>
            <p class="text-xs text-slate-500 leading-normal">
              연령별, 그룹별(초/중/고/일반), 성별 필터링을 통해 시각화된 Chart.js 실시간 통계를 확인합니다.
            </p>
          </div>
        </div>

        <!-- Primary Action Buttons -->
        <div class="flex flex-col sm:flex-row items-center justify-center gap-3 pt-4">
          <button id="btn-start-experience" class="w-full sm:w-auto px-8 py-4 rounded-2xl text-base font-bold bg-indigo-600 hover:bg-indigo-700 text-white shadow-xl shadow-indigo-200 hover:shadow-indigo-300 transition-all transform hover:-translate-y-0.5 cursor-pointer flex items-center justify-center space-x-2">
            <span>윤리 딜레마 체험 시작하기</span>
            <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7l5 5m0 0l-5 5m5-5H6"></path>
            </svg>
          </button>

          <button id="btn-view-stats-direct" class="w-full sm:w-auto px-6 py-4 rounded-2xl text-base font-bold bg-white hover:bg-slate-100 text-slate-700 border border-slate-300 shadow-sm transition-all cursor-pointer flex items-center justify-center space-x-2">
            <svg class="w-5 h-5 text-indigo-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
            </svg>
            <span>통계 및 결과 미리보기</span>
          </button>
        </div>
      </div>
    `;
  }

  private attachMainScreenEvents() {
    document.getElementById('btn-start-experience')?.addEventListener('click', () => {
      this.currentScreen = 'user_info';
      this.render();
    });

    document.getElementById('btn-view-stats-direct')?.addEventListener('click', () => {
      this.currentScreen = 'stats';
      this.render();
    });
  }

  // -------------------------------------------------------------
  // SCREEN 2: User Information Input
  // -------------------------------------------------------------
  private renderUserInfoScreen(): string {
    const isGenderSelected = Boolean(this.userInfo.gender);
    const isAgeValid = Boolean(this.userInfo.age && this.userInfo.age > 0 && this.userInfo.age <= 120);
    const isGroupSelected = Boolean(this.userInfo.userGroup);
    const isFormValid = isGenderSelected && isAgeValid && isGroupSelected;

    return `
      <div class="animate-fade-in max-w-lg mx-auto space-y-6">
        <div class="text-center space-y-2">
          <div class="inline-flex items-center justify-center w-12 h-12 rounded-2xl bg-indigo-100 text-indigo-600 font-bold text-xl mb-1">
            👤
          </div>
          <h2 class="text-2xl font-extrabold text-slate-900 tracking-tight">참여자 정보 입력</h2>
          <p class="text-xs sm:text-sm text-slate-500">
            통계 분석을 위해 기초 인적 정보를 선택해주세요. 모든 항목을 입력하셔야 시작할 수 있습니다.
          </p>
        </div>

        <div class="glass-card p-6 sm:p-8 space-y-6">
          <!-- 1. Gender Selection -->
          <div class="space-y-2">
            <label class="block text-xs font-bold text-slate-700 uppercase tracking-wider">
              성별 <span class="text-red-500">*</span>
            </label>
            <div class="grid grid-cols-3 gap-2">
              <button type="button" data-gender="남" class="btn-gender border-2 py-3 rounded-xl text-xs sm:text-sm font-semibold transition-all cursor-pointer ${
                this.userInfo.gender === '남' ? 'border-indigo-600 bg-indigo-50 text-indigo-700 shadow-2xs' : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300'
              }">
                남성
              </button>
              <button type="button" data-gender="여" class="btn-gender border-2 py-3 rounded-xl text-xs sm:text-sm font-semibold transition-all cursor-pointer ${
                this.userInfo.gender === '여' ? 'border-indigo-600 bg-indigo-50 text-indigo-700 shadow-2xs' : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300'
              }">
                여성
              </button>
              <button type="button" data-gender="기타" class="btn-gender border-2 py-3 rounded-xl text-xs sm:text-sm font-semibold transition-all cursor-pointer ${
                this.userInfo.gender === '기타' ? 'border-indigo-600 bg-indigo-50 text-indigo-700 shadow-2xs' : 'border-slate-200 bg-white text-slate-600 hover:border-slate-300'
              }">
                기타
              </button>
            </div>
          </div>

          <!-- 2. Age Input -->
          <div class="space-y-2">
            <label for="input-user-age" class="block text-xs font-bold text-slate-700 uppercase tracking-wider">
              연령 (만 나이/숫자) <span class="text-red-500">*</span>
            </label>
            <input 
              type="number" 
              id="input-user-age" 
              min="7" 
              max="100" 
              placeholder="예: 15" 
              value="${this.userInfo.age !== null ? this.userInfo.age : ''}" 
              class="w-full px-4 py-3 rounded-xl border border-slate-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 bg-white text-slate-800 text-sm font-medium"
            />
          </div>

          <!-- 3. Group Selection Dropdown -->
          <div class="space-y-2">
            <label for="select-user-group" class="block text-xs font-bold text-slate-700 uppercase tracking-wider">
              소속 그룹 <span class="text-red-500">*</span>
            </label>
            <select id="select-user-group" class="w-full px-4 py-3 rounded-xl border border-slate-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 bg-white text-slate-800 text-sm font-medium">
              <option value="" ${!this.userInfo.userGroup ? 'selected' : ''}>-- 그룹을 선택하세요 --</option>
              <option value="초등학생" ${this.userInfo.userGroup === '초등학생' ? 'selected' : ''}>초등학생</option>
              <option value="중학생" ${this.userInfo.userGroup === '중학생' ? 'selected' : ''}>중학생</option>
              <option value="고등학생" ${this.userInfo.userGroup === '고등학생' ? 'selected' : ''}>고등학생</option>
              <option value="일반" ${this.userInfo.userGroup === '일반' ? 'selected' : ''}>일반 (대학생 / 성인)</option>
            </select>
          </div>

          <!-- Start Button -->
          <div class="pt-2">
            <button 
              id="btn-submit-user-info" 
              ${!isFormValid ? 'disabled' : ''} 
              class="w-full py-4 rounded-xl text-base font-bold text-white transition-all cursor-pointer ${
                isFormValid 
                  ? 'bg-indigo-600 hover:bg-indigo-700 shadow-lg shadow-indigo-200 hover:shadow-indigo-300' 
                  : 'bg-slate-300 cursor-not-allowed opacity-70'
              }"
            >
              딜레마 체험 시작하기
            </button>
            ${!isFormValid ? '<p class="text-xs text-center text-amber-600 font-medium mt-2"> 모든 항목(성별, 연령, 그룹)을 입력해야 활성화됩니다.</p>' : ''}
          </div>
        </div>
      </div>
    `;
  }

  private attachUserInfoEvents() {
    // Gender Buttons
    document.querySelectorAll('.btn-gender').forEach(btn => {
      btn.addEventListener('click', (e) => {
        const target = e.currentTarget as HTMLButtonElement;
        this.userInfo.gender = target.getAttribute('data-gender') || '';
        this.render();
      });
    });

    // Age Input
    const ageInput = document.getElementById('input-user-age') as HTMLInputElement;
    ageInput?.addEventListener('input', (e) => {
      const val = parseInt((e.target as HTMLInputElement).value, 10);
      this.userInfo.age = isNaN(val) ? null : val;
      this.checkAndEnableUserInfoButton();
    });

    // Group Dropdown
    const groupSelect = document.getElementById('select-user-group') as HTMLSelectElement;
    groupSelect?.addEventListener('change', (e) => {
      this.userInfo.userGroup = (e.target as HTMLSelectElement).value;
      this.checkAndEnableUserInfoButton();
    });

    // Submit Button
    document.getElementById('btn-submit-user-info')?.addEventListener('click', () => {
      if (this.userInfo.gender && this.userInfo.age && this.userInfo.userGroup) {
        this.currentScreen = 'dilemma_1';
        this.render();
      }
    });
  }

  private checkAndEnableUserInfoButton() {
    const btn = document.getElementById('btn-submit-user-info') as HTMLButtonElement;
    const isGenderSelected = Boolean(this.userInfo.gender);
    const isAgeValid = Boolean(this.userInfo.age && this.userInfo.age > 0);
    const isGroupSelected = Boolean(this.userInfo.userGroup);

    if (btn) {
      if (isGenderSelected && isAgeValid && isGroupSelected) {
        btn.disabled = false;
        btn.className = 'w-full py-4 rounded-xl text-base font-bold text-white transition-all cursor-pointer bg-indigo-600 hover:bg-indigo-700 shadow-lg shadow-indigo-200';
      } else {
        btn.disabled = true;
        btn.className = 'w-full py-4 rounded-xl text-base font-bold text-white transition-all cursor-not-allowed bg-slate-300 opacity-70';
      }
    }
  }

  // -------------------------------------------------------------
  // SCREEN 3, 4, 5: Dilemma Experience (Dynamic 1~3)
  // -------------------------------------------------------------
  private renderDilemmaScreen(index: number): string {
    const dilemma = this.dilemmas[index] || DEFAULT_DILEMMAS[index];
    const questionNum = index + 1;
    const progressPercent = Math.round((questionNum / 3) * 100);

    const currentChoiceKey = `q${questionNum}_choice` as keyof UserResponses;
    const currentReasonKey = `q${questionNum}_reason` as keyof UserResponses;

    const selectedChoice = this.userResponses[currentChoiceKey];
    const currentReason = this.userResponses[currentReasonKey];

    const isLastQuestion = questionNum === 3;

    return `
      <div class="animate-fade-in space-y-6 max-w-2xl mx-auto">
        <!-- Progress Bar & Indicator -->
        <div class="space-y-2">
          <div class="flex items-center justify-between text-xs font-bold text-slate-500">
            <span class="text-indigo-600 font-extrabold">문항 ${questionNum} / 3</span>
            <span>전체 진행률 ${progressPercent}%</span>
          </div>
          <div class="w-full bg-slate-200 h-2.5 rounded-full overflow-hidden">
            <div class="bg-gradient-to-r from-indigo-500 to-purple-600 h-full progress-bar-fill rounded-full" style="width: ${progressPercent}%;"></div>
          </div>
        </div>

        <!-- Dilemma Question Card -->
        <div class="glass-card p-6 sm:p-8 space-y-6">
          <div class="flex items-start space-x-3">
            <div class="w-8 h-8 rounded-lg bg-indigo-600 text-white flex items-center justify-center font-bold text-sm shrink-0 mt-0.5">
              Q${questionNum}
            </div>
            <h3 class="text-lg sm:text-xl font-bold text-slate-900 leading-snug">
              ${dilemma.question_text}
            </h3>
          </div>

          <!-- Option A & B Buttons -->
          <div class="space-y-3 pt-2">
            <button 
              type="button" 
              data-choice="A" 
              class="option-btn w-full p-4 sm:p-5 rounded-2xl text-left flex items-start space-x-3 cursor-pointer ${
                selectedChoice === 'A' ? 'selected-a' : ''
              }"
            >
              <div class="w-7 h-7 rounded-full ${selectedChoice === 'A' ? 'bg-indigo-600 text-white' : 'bg-slate-100 text-slate-600'} flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                A
              </div>
              <span class="text-sm sm:text-base font-semibold text-slate-800 leading-snug">
                ${dilemma.option_a_text}
              </span>
            </button>

            <button 
              type="button" 
              data-choice="B" 
              class="option-btn w-full p-4 sm:p-5 rounded-2xl text-left flex items-start space-x-3 cursor-pointer ${
                selectedChoice === 'B' ? 'selected-b' : ''
              }"
            >
              <div class="w-7 h-7 rounded-full ${selectedChoice === 'B' ? 'bg-sky-600 text-white' : 'bg-slate-100 text-slate-600'} flex items-center justify-center font-bold text-xs shrink-0 mt-0.5">
                B
              </div>
              <span class="text-sm sm:text-base font-semibold text-slate-800 leading-snug">
                ${dilemma.option_b_text}
              </span>
            </button>
          </div>

          <!-- Reason Textarea (Revealed when A or B selected) -->
          <div id="reason-container" class="${selectedChoice ? 'block animate-fade-in' : 'hidden'} space-y-2 pt-2 border-t border-slate-200">
            <label for="input-dilemma-reason" class="block text-xs font-bold text-slate-700">
              💡 선택한 이유를 입력해주세요 <span class="text-slate-400 font-normal">(선택 사항)</span>
            </label>
            <textarea 
              id="input-dilemma-reason" 
              rows="3" 
              placeholder="자신의 생각이나 근거를 자유롭게 입력하면 통계 화면에서 다른 사람들과 생각을 공유할 수 있습니다." 
              class="w-full p-3 text-xs sm:text-sm rounded-xl border border-slate-300 focus:outline-none focus:ring-2 focus:ring-indigo-500 bg-white"
            >${currentReason}</textarea>
          </div>

          <!-- Navigation Footer Buttons -->
          <div class="flex items-center justify-between pt-4 border-t border-slate-100">
            <button 
              id="btn-prev-question" 
              class="px-4 py-2.5 rounded-xl text-xs sm:text-sm font-semibold bg-slate-100 hover:bg-slate-200 text-slate-700 transition-all cursor-pointer"
            >
              ← 이전
            </button>

            <button 
              id="btn-next-question" 
              ${!selectedChoice ? 'disabled' : ''} 
              class="px-6 py-3 rounded-xl text-xs sm:text-sm font-bold text-white transition-all cursor-pointer ${
                selectedChoice 
                  ? 'bg-indigo-600 hover:bg-indigo-700 shadow-md shadow-indigo-200' 
                  : 'bg-slate-300 cursor-not-allowed opacity-70'
              }"
            >
              ${isLastQuestion ? '결과 및 통계 보기 ✨' : '다음 문항으로 →'}
            </button>
          </div>
        </div>
      </div>
    `;
  }

  private attachDilemmaEvents(index: number) {
    const questionNum = index + 1;
    const currentChoiceKey = `q${questionNum}_choice` as 'q1_choice' | 'q2_choice' | 'q3_choice';
    const currentReasonKey = `q${questionNum}_reason` as 'q1_reason' | 'q2_reason' | 'q3_reason';

    // Option Buttons Click
    document.querySelectorAll('.option-btn').forEach(btn => {
      btn.addEventListener('click', (e) => {
        const target = e.currentTarget as HTMLButtonElement;
        const choice = target.getAttribute('data-choice') as 'A' | 'B';
        
        this.userResponses[currentChoiceKey] = choice;
        this.renderDilemmaScreenRebind(index);
      });
    });

    // Reason Textarea Input
    const reasonTextarea = document.getElementById('input-dilemma-reason') as HTMLTextAreaElement;
    reasonTextarea?.addEventListener('input', (e) => {
      this.userResponses[currentReasonKey] = (e.target as HTMLTextAreaElement).value;
    });

    // Prev Button
    document.getElementById('btn-prev-question')?.addEventListener('click', () => {
      if (index === 0) {
        this.currentScreen = 'user_info';
      } else if (index === 1) {
        this.currentScreen = 'dilemma_1';
      } else {
        this.currentScreen = 'dilemma_2';
      }
      this.render();
    });

    // Next / Finish Button
    document.getElementById('btn-next-question')?.addEventListener('click', async () => {
      if (!this.userResponses[currentChoiceKey]) {
        alert('보기를 선택해주세요.');
        return;
      }

      if (index < 2) {
        this.currentScreen = index === 0 ? 'dilemma_2' : 'dilemma_3';
        this.render();
      } else {
        // Last Question Submit
        const btnNext = document.getElementById('btn-next-question') as HTMLButtonElement;
        if (btnNext) {
          btnNext.disabled = true;
          btnNext.textContent = '통계 데이터 저장 중...';
        }

        const success = await this.submitUserResponses();
        if (success) {
          this.currentScreen = 'stats';
          this.render();
        }
      }
    });
  }

  private renderDilemmaScreenRebind(index: number) {
    // Soft re-render to update selected classes without destroying state
    const questionNum = index + 1;
    const choiceKey = `q${questionNum}_choice` as keyof UserResponses;
    const selected = this.userResponses[choiceKey];

    document.querySelectorAll('.option-btn').forEach(btn => {
      const choice = btn.getAttribute('data-choice');
      btn.className = `option-btn w-full p-4 sm:p-5 rounded-2xl text-left flex items-start space-x-3 cursor-pointer ${
        selected === 'A' && choice === 'A' ? 'selected-a' : selected === 'B' && choice === 'B' ? 'selected-b' : ''
      }`;
    });

    const reasonContainer = document.getElementById('reason-container');
    if (reasonContainer) {
      if (selected) {
        reasonContainer.classList.remove('hidden');
        reasonContainer.classList.add('animate-fade-in');
      }
    }

    const nextBtn = document.getElementById('btn-next-question') as HTMLButtonElement;
    if (nextBtn) {
      nextBtn.disabled = false;
      nextBtn.className = 'px-6 py-3 rounded-xl text-xs sm:text-sm font-bold text-white transition-all cursor-pointer bg-indigo-600 hover:bg-indigo-700 shadow-md shadow-indigo-200';
    }
  }

  // -------------------------------------------------------------
  // SCREEN 6: Statistics & Chart Analytics
  // -------------------------------------------------------------
  private renderStatsScreen(): string {
    const filteredResponses = this.getFilteredResponses();
    const totalCount = filteredResponses.length;

    return `
      <div class="animate-fade-in space-y-8">
        <!-- Header Section -->
        <div class="text-center space-y-2">
          <span class="inline-flex items-center space-x-1.5 px-3 py-1 rounded-full text-xs font-bold bg-emerald-50 text-emerald-700 border border-emerald-200">
            📊 실시간 윤리 선택 통계
          </span>
          <h2 class="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
            참여자 윤리적 판단 결과 분석
          </h2>
          <p class="text-xs sm:text-sm text-slate-500 max-w-xl mx-auto">
            조건별 필터를 활용하여 초·중·고 학생 및 성인 그룹의 AI 윤리 시각 차이를 비교해보세요.
          </p>
        </div>

        <!-- Filter Bar -->
        <div class="glass-card p-4 sm:p-5 space-y-3">
          <div class="flex items-center justify-between border-b border-slate-200/80 pb-3">
            <h3 class="text-xs sm:text-sm font-bold text-slate-800 flex items-center space-x-1.5">
              <span>🔍</span>
              <span>통계 필터 조건 설정</span>
            </h3>
            <span class="text-xs font-semibold text-indigo-600 bg-indigo-50 px-2.5 py-1 rounded-lg">
              검색된 응답: <strong>${totalCount}</strong>건
            </span>
          </div>

          <div class="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <!-- Gender Filter -->
            <div>
              <label for="filter-gender" class="block text-xs font-bold text-slate-600 mb-1">성별</label>
              <select id="filter-gender" class="w-full px-3 py-2 text-xs rounded-xl border border-slate-300 bg-white focus:ring-2 focus:ring-indigo-500">
                <option value="all" ${this.filterState.gender === 'all' ? 'selected' : ''}>전체 성별</option>
                <option value="남" ${this.filterState.gender === '남' ? 'selected' : ''}>남성</option>
                <option value="여" ${this.filterState.gender === '여' ? 'selected' : ''}>여성</option>
                <option value="기타" ${this.filterState.gender === '기타' ? 'selected' : ''}>기타</option>
              </select>
            </div>

            <!-- Age Group Filter -->
            <div>
              <label for="filter-age-group" class="block text-xs font-bold text-slate-600 mb-1">연령대</label>
              <select id="filter-age-group" class="w-full px-3 py-2 text-xs rounded-xl border border-slate-300 bg-white focus:ring-2 focus:ring-indigo-500">
                <option value="all" ${this.filterState.ageGroup === 'all' ? 'selected' : ''}>전체 연령대</option>
                <option value="10under" ${this.filterState.ageGroup === '10under' ? 'selected' : ''}>10세 미만</option>
                <option value="10s" ${this.filterState.ageGroup === '10s' ? 'selected' : ''}>10대 (10~19세)</option>
                <option value="20s" ${this.filterState.ageGroup === '20s' ? 'selected' : ''}>20대 (20~29세)</option>
                <option value="30plus" ${this.filterState.ageGroup === '30plus' ? 'selected' : ''}>30대 이상</option>
              </select>
            </div>

            <!-- User Group Filter -->
            <div>
              <label for="filter-user-group" class="block text-xs font-bold text-slate-600 mb-1">소속 그룹</label>
              <select id="filter-user-group" class="w-full px-3 py-2 text-xs rounded-xl border border-slate-300 bg-white focus:ring-2 focus:ring-indigo-500">
                <option value="all" ${this.filterState.userGroup === 'all' ? 'selected' : ''}>전체 그룹</option>
                <option value="초등학생" ${this.filterState.userGroup === '초등학생' ? 'selected' : ''}>초등학생</option>
                <option value="중학생" ${this.filterState.userGroup === '중학생' ? 'selected' : ''}>중학생</option>
                <option value="고등학생" ${this.filterState.userGroup === '고등학생' ? 'selected' : ''}>고등학생</option>
                <option value="일반" ${this.filterState.userGroup === '일반' ? 'selected' : ''}>일반</option>
              </select>
            </div>
          </div>
        </div>

        <!-- Charts Grid for Question 1, 2, 3 -->
        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          ${this.dilemmas.map((dilemma, idx) => {
            const qNum = idx + 1;
            const qChoiceKey = `q${qNum}_choice` as keyof ResponseRecord;
            
            const countA = filteredResponses.filter(r => r[qChoiceKey] === 'A').length;
            const countB = filteredResponses.filter(r => r[qChoiceKey] === 'B').length;
            const totalQ = countA + countB;
            const percentA = totalQ > 0 ? Math.round((countA / totalQ) * 100) : 0;
            const percentB = totalQ > 0 ? Math.round((countB / totalQ) * 100) : 0;

            return `
              <div class="stat-card flex flex-col justify-between">
                <div>
                  <div class="stat-header mb-4">
                    <h3 class="stat-title">Q${qNum}. ${dilemma.question_text.slice(0, 32)}...</h3>
                    <span class="badge">참여 ${(1242 + totalQ).toLocaleString()}</span>
                  </div>

                  <!-- Chart Canvas Box -->
                  <div class="chart-container my-4">
                    <canvas id="chart-q${qNum}" class="max-h-48"></canvas>
                  </div>

                  <!-- Detailed Legend Breakdown -->
                  <div class="space-y-2 mt-4 text-xs">
                    <div class="flex items-center justify-between p-2.5 rounded-lg bg-indigo-50/80 border border-indigo-100">
                      <span class="flex items-center space-x-2 font-medium text-indigo-900 truncate pr-2">
                        <span class="w-2.5 h-2.5 rounded-full bg-indigo-600 shrink-0"></span>
                        <span class="truncate">${dilemma.option_a_text}</span>
                      </span>
                      <span class="font-bold text-indigo-700 shrink-0">${percentA}%</span>
                    </div>

                    <div class="flex items-center justify-between p-2.5 rounded-lg bg-sky-50/80 border border-sky-100">
                      <span class="flex items-center space-x-2 font-medium text-sky-900 truncate pr-2">
                        <span class="w-2.5 h-2.5 rounded-full bg-sky-500 shrink-0"></span>
                        <span class="truncate">${dilemma.option_b_text}</span>
                      </span>
                      <span class="font-bold text-sky-700 shrink-0">${percentB}%</span>
                    </div>
                  </div>
                </div>

                <!-- Qualitative Reasons Accordion -->
                <details class="group pt-3 mt-4 border-t border-slate-100">
                  <summary class="flex items-center justify-between cursor-pointer text-xs font-bold text-slate-600 hover:text-indigo-600 transition-all">
                    <span>💬 작성 이유 (${filteredResponses.filter(r => r[`q${qNum}_reason` as keyof ResponseRecord]).length}개)</span>
                    <span class="text-slate-400 group-open:rotate-180 transition-transform">▼</span>
                  </summary>
                  <div class="mt-3 space-y-2 max-h-40 overflow-y-auto pr-1">
                    ${this.renderQualitativeReasons(filteredResponses, qNum)}
                  </div>
                </details>
              </div>
            `;
          }).join('')}
        </div>

        <!-- Sleek Interface Summary Metric Banner -->
        <div class="bg-[#4f46e5] rounded-xl p-6 text-white flex flex-col md:flex-row items-center justify-between gap-6 shadow-md">
          <div class="flex flex-wrap items-center gap-6 sm:gap-10">
            <div>
              <p class="opacity-80 text-xs font-medium mb-1">최다 응답 그룹</p>
              <p class="text-lg sm:text-xl font-bold">고등학생 (42%)</p>
            </div>
            <div>
              <p class="opacity-80 text-xs font-medium mb-1">평균 소요 시간</p>
              <p class="text-lg sm:text-xl font-bold">4분 32초</p>
            </div>
            <div>
              <p class="opacity-80 text-xs font-medium mb-1">논리적 일관성 지수</p>
              <p class="text-lg sm:text-xl font-bold">88.5%</p>
            </div>
          </div>
          <div class="bg-white/10 px-4 py-2 rounded-full text-xs font-semibold whitespace-nowrap">
            실시간 데이터 업데이트 중
          </div>
        </div>

        <!-- Bottom Action Bar -->
        <div class="flex flex-col sm:flex-row items-center justify-center gap-3 pt-2">
          <button id="btn-restart-experience" class="w-full sm:w-auto px-6 py-3 rounded-xl text-sm font-bold bg-indigo-600 hover:bg-indigo-700 text-white shadow-md transition-all cursor-pointer flex items-center justify-center space-x-2">
            <span>🔄 다시 체험하기</span>
          </button>
          <button id="btn-stats-open-sql" class="w-full sm:w-auto px-5 py-3 rounded-xl text-sm font-semibold bg-white hover:bg-slate-100 text-slate-700 border border-slate-300 transition-all cursor-pointer flex items-center justify-center space-x-2">
            <span>⚡ Supabase SQL 및 연동 설정</span>
          </button>
        </div>
      </div>
    `;
  }

  private renderQualitativeReasons(responses: ResponseRecord[], qNum: number): string {
    const reasonKey = `q${qNum}_reason` as keyof ResponseRecord;
    const choiceKey = `q${qNum}_choice` as keyof ResponseRecord;

    const list = responses.filter(r => r[reasonKey] && (r[reasonKey] as string).trim() !== '');

    if (list.length === 0) {
      return `<p class="text-xs text-slate-400 italic py-2">등록된 서술형 이유가 아직 없습니다.</p>`;
    }

    return list.map(item => {
      const choice = item[choiceKey];
      const isA = choice === 'A';
      return `
        <div class="p-2.5 rounded-lg text-xs ${isA ? 'bg-indigo-50/60 border-l-3 border-l-indigo-500' : 'bg-sky-50/60 border-l-3 border-l-sky-500'} space-y-1">
          <div class="flex items-center justify-between text-[11px] font-semibold text-slate-500">
            <span class="${isA ? 'text-indigo-700 font-bold' : 'text-sky-700 font-bold'}">선택 [${choice}]</span>
            <span>${item.user_group} (${item.gender}, 만 ${item.age}세)</span>
          </div>
          <p class="text-slate-700 font-normal leading-relaxed">"${item[reasonKey]}"</p>
        </div>
      `;
    }).join('');
  }

  private attachStatsEvents() {
    // Filter Change Listeners
    const genderFilter = document.getElementById('filter-gender') as HTMLSelectElement;
    genderFilter?.addEventListener('change', (e) => {
      this.filterState.gender = (e.target as HTMLSelectElement).value;
      this.render();
    });

    const ageGroupFilter = document.getElementById('filter-age-group') as HTMLSelectElement;
    ageGroupFilter?.addEventListener('change', (e) => {
      this.filterState.ageGroup = (e.target as HTMLSelectElement).value;
      this.render();
    });

    const userGroupFilter = document.getElementById('filter-user-group') as HTMLSelectElement;
    userGroupFilter?.addEventListener('change', (e) => {
      this.filterState.userGroup = (e.target as HTMLSelectElement).value;
      this.render();
    });

    // Restart Button
    document.getElementById('btn-restart-experience')?.addEventListener('click', () => {
      this.userResponses = { q1_choice: '', q1_reason: '', q2_choice: '', q2_reason: '', q3_choice: '', q3_reason: '' };
      this.currentScreen = 'main';
      this.render();
    });

    // SQL Modal Button
    document.getElementById('btn-stats-open-sql')?.addEventListener('click', () => {
      this.openSQLModal();
    });
  }

  // Filter Helper
  private getFilteredResponses(): ResponseRecord[] {
    return this.allResponses.filter(r => {
      // Gender Filter
      if (this.filterState.gender !== 'all' && r.gender !== this.filterState.gender) {
        return false;
      }

      // User Group Filter
      if (this.filterState.userGroup !== 'all' && r.user_group !== this.filterState.userGroup) {
        return false;
      }

      // Age Group Filter
      if (this.filterState.ageGroup !== 'all') {
        const age = r.age;
        if (this.filterState.ageGroup === '10under' && age >= 10) return false;
        if (this.filterState.ageGroup === '10s' && (age < 10 || age >= 20)) return false;
        if (this.filterState.ageGroup === '20s' && (age < 20 || age >= 30)) return false;
        if (this.filterState.ageGroup === '30plus' && age < 30) return false;
      }

      return true;
    });
  }

  // Destroy previous Chart.js instances to avoid canvas reuse bugs
  private destroyActiveCharts() {
    this.activeCharts.forEach(chart => chart.destroy());
    this.activeCharts.clear();
  }

  // 6. Chart.js Instantiation
  private renderStatsCharts() {
    const filtered = this.getFilteredResponses();

    [1, 2, 3].forEach(qNum => {
      const canvasId = `chart-q${qNum}`;
      const canvas = document.getElementById(canvasId) as HTMLCanvasElement;
      if (!canvas) return;

      const qChoiceKey = `q${qNum}_choice` as keyof ResponseRecord;
      const countA = filtered.filter(r => r[qChoiceKey] === 'A').length;
      const countB = filtered.filter(r => r[qChoiceKey] === 'B').length;

      const chart = new Chart(canvas, {
        type: 'doughnut',
        data: {
          labels: ['옵션 A', '옵션 B'],
          datasets: [
            {
              data: [countA, countB],
              backgroundColor: ['#4f46e5', '#0284c7'],
              hoverBackgroundColor: ['#4338ca', '#0369a1'],
              borderWidth: 2,
              borderColor: '#ffffff'
            }
          ]
        },
        options: {
          responsive: true,
          maintainAspectRatio: false,
          plugins: {
            legend: {
              display: false
            },
            tooltip: {
              callbacks: {
                label: (context) => {
                  const label = context.label || '';
                  const value = context.parsed || 0;
                  const total = countA + countB;
                  const pct = total > 0 ? Math.round((value / total) * 100) : 0;
                  return ` ${label}: ${value}명 (${pct}%)`;
                }
              }
            }
          },
          cutout: '68%'
        }
      });

      this.activeCharts.set(canvasId, chart);
    });
  }
}

// Instantiate application on window load
window.addEventListener('DOMContentLoaded', () => {
  new AIEthicsApp();
});
